"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import Link from "next/link";
import Button from "@mui/material/Button"
import { FaGithub } from "react-icons/fa";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Provider store={store}>
        <nav className="bg-black p-8">
          <ul className="flex justify-end reverse space-x-4">
            <li>
              <Link href="/" className="text-white hover:underline">
                <Button>Home</Button>
              </Link>
            </li>
            <li>
              <Link href="/" className="text-white hover:underline">
                <FaGithub size={40} href="https://github.com/Sundaram-Katare/CLI-Guru"/>
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </Provider>  
      </body>
    </html>
  );
}
